-- 创建车位租赁申请表
CREATE TABLE IF NOT EXISTS parking_rental_application (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '申请ID',
    parking_space_id BIGINT NOT NULL COMMENT '车位ID',
    space_no VARCHAR(50) NOT NULL COMMENT '车位编号',
    owner_id BIGINT NOT NULL COMMENT '业主ID',
    owner_name VARCHAR(100) NOT NULL COMMENT '业主姓名',
    contact_phone VARCHAR(20) NOT NULL COMMENT '联系电话',
    vehicle_number VARCHAR(20) NOT NULL COMMENT '车辆号码',
    vehicle_brand VARCHAR(100) COMMENT '车辆品牌',
    vehicle_color VARCHAR(50) COMMENT '车辆颜色',
    rental_start_date DATE NOT NULL COMMENT '期望开始租赁日期',
    rental_end_date DATE COMMENT '期望结束租赁日期',
    rental_months INT DEFAULT 1 COMMENT '租赁月数',
    application_reason TEXT COMMENT '申请原因',
    application_status TINYINT DEFAULT 1 COMMENT '申请状态：1-待审核 2-已通过 3-已驳回',
    review_user_id BIGINT COMMENT '审核人ID',
    review_user_name VARCHAR(100) COMMENT '审核人姓名',
    review_time DATETIME COMMENT '审核时间',
    review_remark VARCHAR(500) COMMENT '审核备注',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    create_by VARCHAR(64) DEFAULT '' COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT '' COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_parking_space_id (parking_space_id),
    KEY idx_owner_id (owner_id),
    KEY idx_application_status (application_status),
    KEY idx_deleted (deleted),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='车位租赁申请表';